### ISSUE TITLE
When I input "how are you" the model will output NA, "how are you?" is ok 

### ISSUE THREAD

**Issue by ILG2021** [VinAIResearch/VinAI_Translate#10]

**Comment by datquocnguyen** [comment]
No, this issue only occurs when using the demo system at https://vinai-translate.vinai.io/, whose back-end models might be unavailable due to limited computational resources.
You can try the models here: https://huggingface.co/spaces/vinai/VinAI_Translate

**Comment by ILG2021** [comment]
Thanks, can you supply a onnx or ct2 version?
