### ISSUE TITLE
Model này làm mất dấu xuống dòng, và do vậy tăng thời gian dịch vì phải tách dòng bằng tay !

### ISSUE THREAD

**Issue by thusinh1969** [VinAIResearch/VinAI_Translate#4]
Model này làm mất dấu xuống dòng, và do vậy tăng thời gian dịch vì phải tách dòng bằng tay !

Có cách nào chỉnh không ?

Nguyên

**Comment by datquocnguyen** [comment]
Try https://vinai-translate.vinai.io/ system that employs the VinAI_Translate models and also preserves the layout and format of the input.

**Comment by thusinh1969** [comment]
Hỏng, cần chạy cho text pieces dạng json cơ bạn. Có con updated version nào giữ lại format không chỉ link với :)

Thanks,
Nguyên
