### ISSUE TITLE
Cont.: Model này làm mất dấu xuống dòng, và do vậy tăng thời gian dịch vì phải tách dòng bằng tay, cần model không mất format chạy local !

### ISSUE THREAD

**Issue by thusinh1969** [VinAIResearch/VinAI_Translate#5]
Cont.: Model này làm mất dấu xuống dòng, và do vậy tăng thời gian dịch vì phải tách dòng bằng tay, cần model không mất format chạy local !

Mình toàn json và long text có "\n" nhiều, mong có con VinAI này. Có dùng Facebook M2M nhưng chưa đạt.

Thanks trước,
Nguyên

**Comment by datquocnguyen** [comment]
You might want to split the long text into shorter ones and translate them one-by-one, then concatenate translated outputs.

**Comment by thusinh1969** [comment]
> You might want to split the long text into shorter ones (by "\n") and translate them one-by-one, then concatenate translated outputs.

...and it will take 40x times longer yes :) Thanks anyway. Dùng Facebook tạm.

**Comment by datquocnguyen** [comment]
Why would it take 40 times longer? Inference time should be similar if you perform batch decoding.
In any case, you will also need to split the long text into shorter segments because the maximum sequence length of the model is limited to 1024 (for both m2m and VinAI Translate).

**Comment by thusinh1969** [comment]
Assumingly you have 40 lines of text, each with \n. That is 40x time translation. Whereby if I can concatenate likes 10-15 \n altogather, that is 10-15 times faster, is is not. Anyway, if there is a model that can preserve format (\n etc...) please let me know (nguyen@hatto.com, a hardcore, old man love AI for 20 years).

**Comment by datquocnguyen** [comment]
A simple trick is to replace "\n" in the input with some special string e.g. "BBBBBB" before translation, and then replace "BBBBBB" in the output with "\n" after translation.
