### ISSUE TITLE
Extract embedding from this model

### ISSUE THREAD

**Issue by quannv-1204** [VinAIResearch/VinAI_Translate#7]
Can this model extract embedding from Vietnamese text?

**Comment by datquocnguyen** [comment]
Yes, you may employ the encoder of the pre-trained `vinai/vinai-translate-vi2en`.

**Comment by quannv-1204** [comment]
hi, can you host an encoder version of pretrained model on SentenceTransformer ? I would be very appreciated it.

**Comment by quannv-1204** [comment]
@datquocnguyen
