### ISSUE TITLE
How to train the model

### ISSUE THREAD

**Issue by leviethung2103** [VinAIResearch/VinAI_Translate#9]
Hello Mr Dat, 

Thank you for providing such a great Viet-Eng translator model. 

I knew that the model is built on Transformer Hugging Face.

Could you kindly help me provide me some instructions or tutorials to train and reproduce the results ? 

Thank you in advance.

**Comment by datquocnguyen** [comment]
The model was built using fairseq, then converted into huggingface transformers.
See the instruction at: https://github.com/facebookresearch/fairseq/tree/main/examples/mbart
